lappend auto_path "C:/lscc/diamond/3.13/data/script"
package require tbtemplate_generation

set ::bali::Para(MODNAME) mipidphy2cmos
set ::bali::Para(PROJECT) crosslink_histo_demo_proj
set ::bali::Para(PACKAGE) {"C:/lscc/diamond/3.13/cae_library/vhdl_packages/vdbs"}
set ::bali::Para(PRIMITIVEFILE) {"C:/lscc/diamond/3.13/cae_library/synthesis/verilog/lifmd.v"}
set ::bali::Para(TFT) {"C:/lscc/diamond/3.13/data/templates/plsitft.tft"}
set ::bali::Para(OUTNAME) mipidphy2cmos_tf
set ::bali::Para(EXT) .v
set ::bali::Para(FILELIST) {"C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/source/topmod.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/byte2pix/byte2pix.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/byte2pix/byte2pix_byte2pixel_bb.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx_dphy_rx.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx_dphy_wrapper.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx_capture_ctrl_bb.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx_dphy_rx_wrap_bb.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx_rx_global_ctrl_bb.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx/csi_dphy_rx_soft_dphy_rx_bb.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/pll_ip/pll_ip.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/ram_dq_ip/ram_dq_ip.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/ip.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/source/mipidphy2cmos.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/source/reset_manager.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/source/pixel2histo.v=work,Verilog_2001" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/source/reset_bridge.v=work,Verilog_2001" }
set ::bali::Para(INCLUDEPATH) {"C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/source" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/byte2pix" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/csi_dphy_rx" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/pll_ip" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip/ram_dq_ip" "C:/Project/Working/FPGA/HOME/Camera/crosslink_histo_demo_proj-main/crosslink_histo_demo_proj-main/ip" }
puts "set parameters done"
::bali::GenerateTbTemplate
