/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 7.5 */
/* Mon Sep 30 07:58:42 2024 */

/* parameterized module instance */
ram_dq_ip __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), 
    .Data( ), .Q( ));
