//Verilog instantiation template

ip _inst (.ram_dq_ip_Address(), .ram_dq_ip_Data(), .ram_dq_ip_Q(), .ram_dq_ip_Clock(), 
   .ram_dq_ip_ClockEn(), .ram_dq_ip_Reset(), .ram_dq_ip_WE(), .byte2pix_dt_i(), 
   .byte2pix_p_odd_o(), .byte2pix_payload_i(), .byte2pix_pd_o(), .byte2pix_wc_i(), 
   .byte2pix_clk_byte_i(), .byte2pix_clk_pixel_i(), .byte2pix_fv_o(), 
   .byte2pix_lp_av_en_i(), .byte2pix_lv_o(), .byte2pix_payload_en_i(), 
   .byte2pix_reset_byte_n_i(), .byte2pix_reset_pixel_n_i(), .byte2pix_sp_en_i(), 
   .csi_dphy_rx_bd_o(), .csi_dphy_rx_dt_o(), .csi_dphy_rx_ecc_o(), .csi_dphy_rx_lp_hs_state_clk_o(), 
   .csi_dphy_rx_lp_hs_state_d_o(), .csi_dphy_rx_payload_o(), .csi_dphy_rx_ref_dt_i(), 
   .csi_dphy_rx_vc_o(), .csi_dphy_rx_wc_o(), .csi_dphy_rx_cd_d0_o(), .csi_dphy_rx_clk_byte_fr_i(), 
   .csi_dphy_rx_clk_byte_hs_o(), .csi_dphy_rx_clk_byte_o(), .csi_dphy_rx_clk_lp_ctrl_i(), 
   .csi_dphy_rx_clk_n_i(), .csi_dphy_rx_clk_p_i(), .csi_dphy_rx_d0_n_i(), 
   .csi_dphy_rx_d0_p_i(), .csi_dphy_rx_d1_n_i(), .csi_dphy_rx_d1_p_i(), 
   .csi_dphy_rx_hs_d_en_o(), .csi_dphy_rx_hs_sync_o(), .csi_dphy_rx_lp_av_en_o(), 
   .csi_dphy_rx_lp_d0_rx_n_o(), .csi_dphy_rx_lp_d0_rx_p_o(), .csi_dphy_rx_lp_d1_rx_n_o(), 
   .csi_dphy_rx_lp_d1_rx_p_o(), .csi_dphy_rx_lp_en_o(), .csi_dphy_rx_payload_en_o(), 
   .csi_dphy_rx_pd_dphy_i(), .csi_dphy_rx_pll_lock_i(), .csi_dphy_rx_reset_byte_fr_n_i(), 
   .csi_dphy_rx_reset_byte_n_i(), .csi_dphy_rx_reset_lp_n_i(), .csi_dphy_rx_reset_n_i(), 
   .csi_dphy_rx_sp_en_o(), .csi_dphy_rx_term_clk_en_o(), .pll_ip_CLKI(), 
   .pll_ip_CLKOP(), .pll_ip_CLKOS(), .pll_ip_LOCK());