//===========================================================================
// Verilog file generated by Clarity Designer    10/04/2024    08:07:36  
// Filename  : dut_inst.v                                                
// IP package: Byte to Pixel Converter 1.3                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

byte2pixel_rev_1 byte2pixel_rev_1_inst (
    .reset_byte_n_i          (reset_byte_n_i),
    .reset_pixel_n_i         (reset_pixel_n_i),
    .clk_byte_i              (clk_byte_i),
    .clk_pixel_i             (clk_pixel_i),
    .sp_en_i                 (sp_en_i),
    .dt_i                    (dt_i),
    .lp_av_en_i              (lp_av_en_i),
    .payload_en_i            (payload_en_i),
    .payload_i               (payload_i),
    .wc_i                    (wc_i),
    .fv_o                    (fv_o),
    .lv_o                    (lv_o),
    .pd_o                    (pd_o),
    .p_odd_o                 (p_odd_o)
);

