

// TOOL:     vlog2tf
// DATE:     Fri Sep 27 08:36:20 2024
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   mipidphy2cmos
// DESIGN:   mipidphy2cmos
// FILENAME: mipidphy2cmos_tf.v
// PROJECT:  crosslink_histo_demo_proj
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module mipidphy2cmos_tf();

// Inputs
    reg reset_n_i;
    reg clk_pixel_i;
    reg pll_lock_i;


// Outputs
    wire [15:0] pd0_o;
    wire fv_o;
    wire lv_o;
    wire rx_clk_byte_fr_o;
    wire rx_payload_en;
    wire [15:0] tp_data;


// Bidirs
    wire rx_clk_p_i;
    wire rx_clk_n_i;
    wire rx_d0_p_i;
    wire rx_d0_n_i;
    wire rx_d1_p_i;
    wire rx_d1_n_i;


// Instantiate the UUT
// Please check and add your parameters manually
    mipidphy2cmos UUT (
        .reset_n_i(reset_n_i), 
        .rx_clk_p_i(rx_clk_p_i), 
        .rx_clk_n_i(rx_clk_n_i), 
        .rx_d0_p_i(rx_d0_p_i), 
        .rx_d0_n_i(rx_d0_n_i), 
        .rx_d1_p_i(rx_d1_p_i), 
        .rx_d1_n_i(rx_d1_n_i), 
        .pd0_o(pd0_o), 
        .fv_o(fv_o), 
        .lv_o(lv_o), 
        .rx_clk_byte_fr_o(rx_clk_byte_fr_o), 
        .clk_pixel_i(clk_pixel_i), 
        .pll_lock_i(pll_lock_i), 
        .rx_payload_en(rx_payload_en), 
        .tp_data(tp_data)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            reset_n_i = 0;
            clk_pixel_i = 0;
            pll_lock_i = 0;
    end

endmodule // mipidphy2cmos_tf